#!/bin/bash

echo "Disable Nginx on port 80"
rm -f /etc/nginx/sites-enabled/force_https
kill -HUP $(pidof nginx)

sleep 3

echo "Try to renew certificates"
letsencrypt renew --agree-tos

echo "Re-enable Nginx on port 80"
ln -s /etc/nginx/sites-available/force_https /etc/nginx/sites-enabled/
kill -HUP $(pidof nginx)
