#!/bin/bash

if [ -z $DOMAIN_NAME ]; then
  echo "Error: \$DOMAIN_NAME must be set to setup this container"
  exit 1
fi

if [ -z $ADMIN_EMAIL ]; then
  echo "Error: \$ADMIN_EMAIL must be set to setup this container"
  exit 1
fi

if [ -d /etc/letsencrypt/live/$DOMAIN_NAME ]; then
  echo -n "Some keys & certificates already exist for \`$DOMAIN_NAME\`. Overwrite? [y/N]"
  read overwrite
  if [ ".$overwrite" = ".y" ]; then
    rm -rf /etc/letsencrypt/*
  else
    exit 1
  fi
fi

echo "Fecthing SSL certs from Let's Encrypt"
letsencrypt certonly --standalone --non-interactive --agree-tos --email $ADMIN_EMAIL --domain $DOMAIN_NAME
